# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# dfs.py
# Created on: 2016-10-14 16:17:13.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: dfs <temp> 
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy,os
arcpy.env.overwriteOutput = True
# Load required toolboxes
# arcpy.ImportToolbox("Model Functions")

# Script arguments
# temp = arcpy.GetParameterAsText(0)
# result = arcpy.GetParameterAsText(1)

temp = r"D:\temp"
result = r"D:\temp\rrr"
# if temp == '#' or not temp:
#     temp = "D:\\temp" # provide a default value if unspecified

# Local variables:
FeatureClass = temp
cun = FeatureClass
FeatureClass_Layer = cun
FeatureClass_Layer__2_ = FeatureClass_Layer
cun_Eliminate = FeatureClass_Layer__2_
Name = temp
arcpy.env.worksapce = temp

# Process: Iterate Feature Classes
# arcpy.IterateFeatureClasses_mb(temp, "", "", "NOT_RECURSIVE")
fcs = arcpy.ListFeatureClasses()
for fc in fcs:
    # Process: Calculate Field
    arcpy.CalculateField_management(fc, "TBMJ", "\"!SHAPE.AREA!\"", "PYTHON_9.3", "")
    
    # Process: Make Feature Layer
    arcpy.MakeFeatureLayer_management(fc, FeatureClass_Layer, "", "", "FID FID VISIBLE NONE;Shape Shape VISIBLE NONE;Id Id VISIBLE NONE;DSMC DSMC VISIBLE NONE;QXMC QXMC VISIBLE NONE;XZMC XZMC VISIBLE NONE;CUNMC CUNMC VISIBLE NONE;CUNDM CUNDM VISIBLE NONE;GCUNDM GCUNDM VISIBLE NONE;TBLXDM TBLXDM VISIBLE NONE;TBLXMC TBLXMC VISIBLE NONE;SFYF SFYF VISIBLE NONE;YFBH YFBH VISIBLE NONE;YFDKBH YFDKBH VISIBLE NONE;XZB XZB VISIBLE NONE;YZB YZB VISIBLE NONE;TBMJ TBMJ VISIBLE NONE;QZW QZW VISIBLE NONE;QZWMJ QZWMJ VISIBLE NONE;QCYZW QCYZW VISIBLE NONE;QCYZWMJ QCYZWMJ VISIBLE NONE;CBZW CBZW VISIBLE NONE;CBZWMJ CBZWMJ VISIBLE NONE;CCYZW CCYZW VISIBLE NONE;CCYZWMJ CCYZWMJ VISIBLE NONE;XBZW XBZW VISIBLE NONE;XBZWMJ XBZWMJ VISIBLE NONE;XCYZW XCYZW VISIBLE NONE;XCYZWMJ XCYZWMJ VISIBLE NONE;SNYD SNYD VISIBLE NONE;SNFZCS SNFZCS VISIBLE NONE;SNZWMC SNZWMC VISIBLE NONE;SNZWMJ SNZWMJ VISIBLE NONE;JCYX JCYX VISIBLE NONE;NHXM NHXM VISIBLE NONE;BZ BZ VISIBLE NONE;area area VISIBLE NONE;Shape_Leng Shape_Leng VISIBLE NONE;Shape_Area Shape_Area VISIBLE NONE")
    
    # Process: Select Layer By Attribute
    arcpy.SelectLayerByAttribute_management(FeatureClass_Layer, "NEW_SELECTION", "\"TBMJ\" <=66.7")
    
    # Process: Eliminate
    Eliminate_Result = os.path.join(result,fc)
    arcpy.Eliminate_management(FeatureClass_Layer, Eliminate_Result, "AREA", "", "")

