# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# clip.py
# Created on: 2014-12-30 10:43:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

arcpy.env.workspace = r"D:\test_envi\TIFF"
#Output_Extent = r"D:\test\nn\ZD_Box_new.shp"
Output_Raster_Dataset = r"D:\test_envi\Clip_Part"
# Local variables:
print "start"
rasts = arcpy.ListRasters()
for rast in  rasts:
        print str(rast)
        #Input_Raster = r"D:\test\nn\raster"
        name = str(rast)[:-4]
        print name

        Output_Raster_name = Output_Raster_Dataset + '\\' + str(name) + '.tif'
        # Process: Clip
        arcpy.Clip_management(rast, "", Output_Raster_name, r"D:\test_envi\AreaBox\Area.shp", "65536", "ClippingGeometry", "NO_MAINTAIN_EXTENT")

print "finish"

