# -*- coding: cp936 -*-
# ---------------------------------------------------------------------------
# LjTp.py
# Created on: 2015-01-06 15:43:16.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
'''
新建数据库
遍历工作空间里的shp文件
以shp文件名新建数据集，并向该数据集导入这个shp
对数据集创建拓扑                CreateTopology_management
向拓扑结构添加数据集里的shp      AddFeatureClassToTopology_management
向拓扑结构添加拓扑规则          AddRuleToTopology_management
验证拓扑                       ValidateTopology_management
'''
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arceditor
# Import arcpy module
import arcpy,os



FolderPath = r"G:\TEST\平滑\topo"
Folders = os.listdir(FolderPath)
print "start"
for Folder in Folders:
    shpFolder = os.path.join(FolderPath,Folder)
    ifcf = Folder + "_地类更新.shp"
    print "ifcf:",ifcf
    ifc = os.path.join(shpFolder,ifcf)
#     print "ifc:",ifc
    
    Coordinate_System = os.path.join(shpFolder,Folder + "_地类更新.prj")
#     print Coordinate_System
    File_GDB_Name = "ZD_landUse_NewShp.gdb"
    Geodatabase = os.path.join(FolderPath,File_GDB_Name)
#     print Geodatabase
    try:
        #新建数据库
        arcpy.CreateFileGDB_management(FolderPath, File_GDB_Name, "CURRENT")
    except:
        print "数据库已经建好"
        
    
    

    
    
    
    out_dataset_path = Geodatabase
    out_name = str(ifcf[:-4])   #数据集名称
    print "数据集名称:" + str(out_name)
    #创建数据集
    arcpy.CreateFeatureDataset_management(out_dataset_path, out_name, Coordinate_System)

    #向数据集导入shp
    in_features = ifc  #导入的shp名称
    out_path = os.path.join(Geodatabase,out_name)   #shp导入的数据集位置
    #print u"shp导入的数据集位置:" + str(out_path)
    out_name = str(ifcf[:-4]) + "_ToPo"    #导入后shp的名称
    #print u"导入后shp的名称:" + str(out_name)
    arcpy.FeatureClassToFeatureClass_conversion (in_features, out_path, out_name)


    # Process: Create Topology
    Topo_name = str(ifcf[:-4]) + "_ToPology" #拓扑结构的名称
    #print u"拓扑结构的名称:" + str(Topo_name)
    arcpy.CreateTopology_management(out_path, Topo_name, "")   #zhiduo_tp  拓扑结构

    # Process: Add Feature Class To Topology
    Topology = os.path.join(out_path,Topo_name)  # 拓扑结构的路径
    ##print u"拓扑结构的路径:" + str(Topology)
    ToPoShp = os.path.join(out_path,out_name)    # 要做拓扑的数据集里的shp
    ##print u"要做拓扑的数据集里的shp:" + str(ToPoShp)
    arcpy.AddFeatureClassToTopology_management(Topology, ToPoShp, "1", "1")

    # Process: Add Rule To Topology
    arcpy.AddRuleToTopology_management(Topology, "Must Not Have Gaps (Area)", ToPoShp, "", "", "")
    #print u"正在添加 Must Not Have Gaps 规则"
    arcpy.AddRuleToTopology_management(Topology, "Must Not Overlap (Area)", ToPoShp, "", "", "")
    #print u"正在添加 Must Not Overlap 规则"

    # Process: Validate Topology
    try:
        arcpy.ValidateTopology_management(Topology, "true")
    except:
        print str(ifcf) + "的拓扑未成功验证，请人工重新建立拓扑。"

    print "拓扑验证完成" + '\n'
    
print "finish"



